AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for ECS task
Parameters:
  Env:
    Type: String
Resources:
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-task-${Env}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SSMRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParametersByPath
                Resource:
                  - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/myapp/*
      Tags:
        - Key: Env
          Value: !Ref Env
Outputs:
  TaskRoleArn:
    Description: ARN of the task role
    Value: !GetAtt TaskRole.Arn
