AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for ECS task execution
Parameters:
  Env:
    Type: String
Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ecs-task-exec-${Env}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Tags:
        - Key: Env
          Value: !Ref Env
Outputs:
  TaskExecutionRoleArn:
    Description: ARN of the task execution role
    Value: !GetAtt TaskExecutionRole.Arn
